name: Test

on: [push]

env:
  # Not sure these are actually being passed down to rails, set them as the default in database.yml
  DB_HOST: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: postgres

jobs:
  product_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
          bundler-cache: true
      - name: Bundle Install
      run: 
          gem install bundler
          bundle install 
      - name: Lint  rubocop
        run: 
          rubocop 
      - name: Run rails tests
        run:            
          RAILS_ENV=test rails db:create && RAILS_ENV=test rails db:migrate && rails rspec


          